<?php
function searchYoutube($q)
{
	$q = urlencode($q); // url encodekan
	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();

	curl_setopt($ch, CURLOPT_URL, 'https://www.googleapis.com/youtube/v3/search' .
		'?part=snippet&maxResults=10' .
		'&q=' . $q .
		'&key=[AIzaSyDmbqW5Egy2HWw01o98LMENPloa1vr5W8g]');
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

	curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

	$headers = array();
	$headers[] = 'Accept: application/json';
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

	$result = curl_exec($ch); // format json
	if (curl_errno($ch)) {
		echo 'Error:' . curl_error($ch);
	}
	curl_close($ch);
	return json_decode($result, true); // returnkan dalam bentuk array assosiatif
}

$keyword = "UNIKOM";
$response = searchYoutube($keyword);
echo "<pre>";
print_r($response);
