<?php
function searchYoutube($q){
	$q=urlencode($q);// url encodekan
	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();

	curl_setopt($ch, CURLOPT_URL, 'https://www.googleapis.com/youtube/v3/search'.
								  '?part=snippet&maxResults=10'.
								  '&q='.$q.
								  '&key=[YOUR_API_KEY]');
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
	curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);

	curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

	$headers = array();
	$headers[] = 'Accept: application/json';
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

	$result = curl_exec($ch); // format json
	if (curl_errno($ch)) {
		echo 'Error:' . curl_error($ch);
	}
	curl_close($ch);
	return json_decode($result,true);// returnkan dalam bentuk array assosiatif
}
?>
<!doctype html>
<head><title>Pencarian youtube</title></head>
<body>
<?php
$keyword="UNIKOM";
$response=searchYoutube($keyword);
?>
<h1>Hasil Pencarian <?php echo $keyword;?></h1>
<?php
$listVideo=$response["items"];// ambil field items dari $response
foreach($listVideo as $video){
	echo "<div>";
	echo "<h5>".$video["snippet"]["title"]."</h5>";
	if($video["id"]["kind"]=="youtube#video")
		echo "<a href=\"https://www.youtube.com/watch?v=".$video["id"]["videoId"]."\">";
	else
	if($video["id"]["kind"]=="youtube#channel")
		echo "<a href=\"https://www.youtube.com/channel/".$video["id"]["channelId"]."\">";
	echo "<img src=\"".$video["snippet"]["thumbnails"]["default"]["url"]."\">";
	echo "</a>";
	echo "</div>";
}
?>